CREATE DATABASE EMPLOYEMANAGEMENT;
USE EMPLOYEMANAGEMENT;

CREATE TABLE EMPLOYEEINFO(
EMPL_Id INT PRIMARY KEY AUTO_INCREMENT,
EMP_NAME VARCHAR(20) NOT NULL,
EMAIL VARCHAR(40) UNIQUE,
SALARY INT CHECK(SALARY BETWEEN 15000 AND 80000),
CITY VARCHAR(20) CHECK(CITY IN("MUMBAI","PUNE","NAGPUR")),
STATE VARCHAR(20) DEFAULT "MAHARASHTRA",
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

